import { Supplier, Customer, InventoryState, Purchase, Sale, PassbookEntry, EmptyCrateLog, WastageLog } from '../types';

const todayStr = new Date().toISOString().slice(0, 10);
const yesterdayDate = new Date();
yesterdayDate.setDate(yesterdayDate.getDate() - 1);
const yesterdayStr = yesterdayDate.toISOString().slice(0, 10);

const twoDaysAgoDate = new Date();
twoDaysAgoDate.setDate(twoDaysAgoDate.getDate() - 2);
const twoDaysAgoStr = twoDaysAgoDate.toISOString().slice(0, 10);

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-101',
    name: 'Salem Farmers Co-operative',
    phone: '+91 9443312345',
    address: 'Salem Mandi Gate 4, APMC Yard',
    pendingBalance: 18500,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sup-102',
    name: 'Hosur Tomato Orchards',
    phone: '+91 9842254321',
    address: 'Hosur Highway Farm 12',
    pendingBalance: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sup-103',
    name: 'Madanapalle Wholesale Produce',
    phone: '+91 9789012345',
    address: 'Madanapalle Yard Stall 8',
    pendingBalance: 32000,
    createdAt: new Date().toISOString(),
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-201',
    name: 'Ramesh Retail Veggies',
    phone: '+91 9876543210',
    shopLocation: 'Market Yard Stall 12',
    defaultSellingRateSmall: 340,
    defaultSellingRateBig: 580,
    pendingBalance: 14200,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust-202',
    name: 'Venkateshwara Supermarket',
    phone: '+91 9988776655',
    shopLocation: 'Indiranagar 100ft Rd',
    defaultSellingRateSmall: 350,
    defaultSellingRateBig: 600,
    pendingBalance: 8500,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust-203',
    name: 'Modern Hotel & Dining',
    phone: '+91 9123456789',
    shopLocation: 'Commercial Street',
    defaultSellingRateSmall: 330,
    defaultSellingRateBig: 560,
    pendingBalance: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cust-204',
    name: 'Lakshmi Organic Store',
    phone: '+91 9445566778',
    shopLocation: 'Gandhi Nagar Main Rd',
    defaultSellingRateSmall: 360,
    defaultSellingRateBig: 620,
    pendingBalance: 5800,
    createdAt: new Date().toISOString(),
  },
];

export const initialInventory: InventoryState = {
  smallCratesCount: 145,
  bigCratesCount: 80,
  smallAvgCost: 280,
  bigAvgCost: 480,
  gradeStocks: [
    { crateSize: 'Small', grade: 'Grade A (Top Red)', count: 65, avgCost: 290 },
    { crateSize: 'Small', grade: 'Grade B (Medium)', count: 80, avgCost: 270 },
    { crateSize: 'Big', grade: 'Grade A (Top Red)', count: 45, avgCost: 490 },
    { crateSize: 'Big', grade: 'Grade B (Medium)', count: 35, avgCost: 460 },
  ],
};

export const initialPurchases: Purchase[] = [
  {
    id: 'pur-001',
    purchaseNo: 'PUR-1001',
    date: twoDaysAgoStr,
    supplierId: 'sup-101',
    supplierName: 'Salem Farmers Co-operative',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade A (Top Red)', quantity: 100, ratePerCrate: 270, total: 27000 },
      { crateSize: 'Big', grade: 'Grade A (Top Red)', quantity: 50, ratePerCrate: 470, total: 23500 },
    ],
    totalAmount: 50500,
    paidAmount: 32000,
    balanceAdded: 18500,
    notes: 'Direct farm arrival via Lorry AP-04',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pur-002',
    purchaseNo: 'PUR-1002',
    date: yesterdayStr,
    supplierId: 'sup-102',
    supplierName: 'Hosur Tomato Orchards',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade B (Medium)', quantity: 120, ratePerCrate: 285, total: 34200 },
      { crateSize: 'Big', grade: 'Grade B (Medium)', quantity: 60, ratePerCrate: 490, total: 29400 },
    ],
    totalAmount: 63600,
    paidAmount: 63600,
    balanceAdded: 0,
    notes: 'Paid in full via UPI Bank transfer',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pur-003',
    purchaseNo: 'PUR-1003',
    date: todayStr,
    supplierId: 'sup-103',
    supplierName: 'Madanapalle Wholesale Produce',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade A (Top Red)', quantity: 80, ratePerCrate: 290, total: 23200 },
      { crateSize: 'Big', grade: 'Grade A (Top Red)', quantity: 40, ratePerCrate: 500, total: 20000 },
    ],
    totalAmount: 43200,
    paidAmount: 11200,
    balanceAdded: 32000,
    notes: 'Morning lorry arrival',
    createdAt: new Date().toISOString(),
  },
];

export const initialSales: Sale[] = [
  {
    id: 'sale-001',
    invoiceNo: 'TSK-1001',
    date: twoDaysAgoStr,
    customerId: 'cust-201',
    customerName: 'Ramesh Retail Veggies',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade A (Top Red)', quantity: 30, ratePerCrate: 340, total: 10200 },
      { crateSize: 'Big', grade: 'Grade A (Top Red)', quantity: 15, ratePerCrate: 580, total: 8700 },
    ],
    totalAmount: 18900,
    paidAmount: 10000,
    balanceAdded: 8900,
    paymentMethod: 'Cash',
    notes: 'Morning dispatch',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sale-002',
    invoiceNo: 'TSK-1002',
    date: yesterdayStr,
    customerId: 'cust-202',
    customerName: 'Venkateshwara Supermarket',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade B (Medium)', quantity: 25, ratePerCrate: 350, total: 8750 },
      { crateSize: 'Big', grade: 'Grade B (Medium)', quantity: 10, ratePerCrate: 600, total: 6000 },
    ],
    totalAmount: 14750,
    paidAmount: 6250,
    balanceAdded: 8500,
    paymentMethod: 'UPI',
    notes: 'Supermarket delivery vehicle',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sale-003',
    invoiceNo: 'TSK-1003',
    date: yesterdayStr,
    customerId: 'cust-203',
    customerName: 'Modern Hotel & Dining',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade A (Top Red)', quantity: 40, ratePerCrate: 330, total: 13200 },
    ],
    totalAmount: 13200,
    paidAmount: 13200,
    balanceAdded: 0,
    paymentMethod: 'Cash',
    notes: 'Settled in full on delivery',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sale-004',
    invoiceNo: 'TSK-1004',
    date: todayStr,
    customerId: 'cust-201',
    customerName: 'Ramesh Retail Veggies',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade A (Top Red)', quantity: 20, ratePerCrate: 340, total: 6800 },
      { crateSize: 'Big', grade: 'Grade A (Top Red)', quantity: 10, ratePerCrate: 580, total: 5800 },
    ],
    totalAmount: 12600,
    paidAmount: 7300,
    balanceAdded: 5300,
    paymentMethod: 'Cash',
    notes: 'Today morning mandi dispatch',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sale-005',
    invoiceNo: 'TSK-1005',
    date: todayStr,
    customerId: 'cust-204',
    customerName: 'Lakshmi Organic Store',
    lineItems: [
      { crateSize: 'Small', grade: 'Grade A (Top Red)', quantity: 15, ratePerCrate: 360, total: 5400 },
      { crateSize: 'Big', grade: 'Grade A (Top Red)', quantity: 8, ratePerCrate: 620, total: 4960 },
    ],
    totalAmount: 10360,
    paidAmount: 4560,
    balanceAdded: 5800,
    paymentMethod: 'UPI',
    notes: 'Organic store daily stock',
    createdAt: new Date().toISOString(),
  },
];

export const initialPassbookEntries: PassbookEntry[] = [
  {
    id: 'pb-101',
    date: twoDaysAgoStr,
    entityType: 'Customer',
    entityId: 'cust-201',
    entityName: 'Ramesh Retail Veggies',
    type: 'Debit',
    amount: 18900,
    runningBalance: 8900,
    transactionType: 'Sale',
    referenceId: 'TSK-1001',
    notes: 'Sale Bill #TSK-1001 (Paid Rs 10000)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pb-102',
    date: yesterdayStr,
    entityType: 'Customer',
    entityId: 'cust-202',
    entityName: 'Venkateshwara Supermarket',
    type: 'Debit',
    amount: 14750,
    runningBalance: 8500,
    transactionType: 'Sale',
    referenceId: 'TSK-1002',
    notes: 'Sale Bill #TSK-1002 (Paid Rs 6250)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pb-103',
    date: todayStr,
    entityType: 'Customer',
    entityId: 'cust-201',
    entityName: 'Ramesh Retail Veggies',
    type: 'Debit',
    amount: 12600,
    runningBalance: 14200,
    transactionType: 'Sale',
    referenceId: 'TSK-1004',
    notes: 'Sale Bill #TSK-1004 (Paid Rs 7300)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pb-104',
    date: todayStr,
    entityType: 'Customer',
    entityId: 'cust-204',
    entityName: 'Lakshmi Organic Store',
    type: 'Debit',
    amount: 10360,
    runningBalance: 5800,
    transactionType: 'Sale',
    referenceId: 'TSK-1005',
    notes: 'Sale Bill #TSK-1005 (Paid Rs 4560)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pb-201',
    date: twoDaysAgoStr,
    entityType: 'Supplier',
    entityId: 'sup-101',
    entityName: 'Salem Farmers Co-operative',
    type: 'Credit',
    amount: 50500,
    runningBalance: 18500,
    transactionType: 'Purchase',
    referenceId: 'PUR-1001',
    notes: 'Purchase Bill #PUR-1001 (Paid Rs 32000)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pb-202',
    date: todayStr,
    entityType: 'Supplier',
    entityId: 'sup-103',
    entityName: 'Madanapalle Wholesale Produce',
    type: 'Credit',
    amount: 43200,
    runningBalance: 32000,
    transactionType: 'Purchase',
    referenceId: 'PUR-1003',
    notes: 'Purchase Bill #PUR-1003 (Paid Rs 11200)',
    createdAt: new Date().toISOString(),
  },
];

export const initialEmptyCrateLogs: EmptyCrateLog[] = [
  {
    id: 'crate-101',
    date: twoDaysAgoStr,
    entityType: 'Customer',
    entityId: 'cust-201',
    entityName: 'Ramesh Retail Veggies',
    crateSize: 'Small',
    action: 'Given_To_Customer',
    quantity: 30,
    smallBalanceAfter: 30,
    bigBalanceAfter: 0,
    notes: 'Issued with Bill TSK-1001',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'crate-102',
    date: yesterdayStr,
    entityType: 'Customer',
    entityId: 'cust-201',
    entityName: 'Ramesh Retail Veggies',
    crateSize: 'Small',
    action: 'Returned_By_Customer',
    quantity: 15,
    smallBalanceAfter: 15,
    bigBalanceAfter: 0,
    notes: 'Returned 15 empty crates in morning lorry',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'crate-103',
    date: todayStr,
    entityType: 'Customer',
    entityId: 'cust-202',
    entityName: 'Venkateshwara Supermarket',
    crateSize: 'Big',
    action: 'Given_To_Customer',
    quantity: 10,
    smallBalanceAfter: 0,
    bigBalanceAfter: 10,
    notes: 'Issued with Bill TSK-1002',
    createdAt: new Date().toISOString(),
  },
];

export const initialWastageLogs: WastageLog[] = [];
